# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171206_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
    ]
